name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  ci-cd:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: "Init repository"
        uses: actions/checkout@v2

      - name: "Setup Node"
        uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - name: "Install dependencied"
        run: npm install

      - name: "Build app"
        run: npm run build

      - name: "Install ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: "Install dpl"
        run: gem install dpl

      # - name: "Run tests"
      #   run: sudo npm run test --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: "Deploy to heroku"
        uses: dpl --provider=heroku --app=${{secrets.HEROKU_APP}} --api-key=${{secrets.HEROKU_API_KEY}} --skip_cleanup=true